export const getUsers=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error.message);
    }
}

export const getUser=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error.message);
    }
}
export const createUsers=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error.message);
    }
}

export const updateUsers=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error.message);
    }
}

export const softDeleteUsers=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error.message);
    }
}

export const deleteUsers=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error.message);
    }
}

export const changeUsersRole=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error.message);
    }
}